name: Mirror Repository to GCP Source Repository

on:
  push:
    branches:
      - main # Substitua pelo nome da branch que deseja observar no Github

env:
  DEST_BRANCH: main # Substitua pelo nome da branch de destino no repositório do GCP

jobs:
  mirror-to-remote:
    runs-on: ubuntu-latest

    steps:

    - name: Obter IP externo
      run: |
        EXTERNAL_IP=$(curl -s https://ipinfo.io/ip)
        echo "O endereço IP externo é: $EXTERNAL_IP"

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configurar SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CLOUD_BUILD_PRIVATE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 2022 -H source.developers.google.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Clonar repositório de destino
      run: |
        git clone ssh://leonardo.lauretti@santodigital.com.br@source.developers.google.com:2022/p/apostaganha-staging/r/test-cloud-build dest
        cd dest
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout $DEST_BRANCH 2>/dev/null || git checkout -b $DEST_BRANCH

    - name: Sincronizar repositório
      run: |
        rsync -av --exclude=".git" ../ dest/
        cd dest
        git add .
        git commit -m "Sincronização a partir do Github"
        git push -u origin $DEST_BRANCH
